### PR TITLE
Add domcloud.co

### PR DESCRIPTION
**Pull request by willnode**
This is a PaaS that I built myself. Thanks for creating this list!

### CODE REVIEW

**Comment by anandrmedia** [comment]
does it include a free plan?

**Comment by willnode** [comment]
Yes, and I intend to continue doing so.

**Comment by willnode** [comment]
Added explanation https://domcloud.co/docs/intro/free-plan/

**Comment by anandrmedia** [comment]
Does it have a database service?

**Comment by willnode** [comment]
Yes, MySQL and Postgres.

... I forgot to mention that in docs, thanks.

**Review by anandrmedia — APPROVED** [review]

**Pull request merged**
